# Create Service
POST http://localhost:3002/api/services
Content-Type: application/json

{
  "name": "test2",
  "host": "localhost",
  "port": 3003,
  "heathPath": "/api/healthy"
}

# Update Service
PUT http://localhost:3002/api/services/5
Content-Type: application/json

{
  "name": "transport"
}

# List Service
GET http://localhost:3002/api/services

# Detail Service
GET http://localhost:3002/api/services/9

# Check Health State
GET http://localhost:3002/api/services/9/health

# Delete Service
DELETE http://localhost:3002/api/services/6
