# Create Action
POST http://localhost:3002/api/actions
Content-Type: application/json

{
  "name": "New Token",
  "apiPath": "/api/jwt",
  "requestMethod": "POST",
  "serviceId": 40
}

# Get Actions without filters
GET http://localhost:3002/api/actions

# Get Actions with filters
GET http://localhost:3002/api/actions?filter_by=serviceId&filter_value=40

# Get Actions with search
GET http://localhost:3002/api/actions?search=Token

# Get Actions with search and filters
GET http://localhost:3002/api/actions?search=Token&filter_by=serviceId&filter_value=41

# Get Action Detail
GET http://localhost:3002/api/actions/21

# Update Action
PUT http://localhost:3002/api/actions/22
Content-Type: application/json

{
  "name": "New Updated Token Name"
}

# Delete Action
DELETE http://localhost:3002/api/actions/21

